name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libssl-dev libjpeg-dev zlib1g-dev libffi8 liblzma-dev uuid-dev
          sudo apt install -y openjdk-17-jdk 

      - name: Setup Python and Buildozer
        run: |
          pip3 install --user --upgrade buildozer cython==0.29.36 virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Force build command
          yes | buildozer android debug
          
          # 🔱 FORCE FIND: Ye command APK ko dhoond kar 'brahmastra.apk' naam se root mein layegi
          echo "Looking for APK..."
          find . -name "*.apk" -exec cp {} ./brahmastra.apk \;
          
          # Check agar file mili ya nahi (Debug ke liye)
          ls -lh ./brahmastra.apk || echo "APK NOT FOUND IN ROOT"
        continue-on-error: false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Brahmastra-Final-APK
          # Ab server ko sirf ye ek file uthani hai, wo bhatkega nahi
          path: brahmastra.apk
